In [31]:
import numpy as np
import pandas as pd
import sklearn
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import mord
from mord import LogisticAT

In [3]:
df = pd.read_excel('LogisticRegression.xlsx',sheet_name='nominal')

In [4]:
df.head()

ses  write      prog
0     low     35  vocation
1  middle     33   general
2    high     39  vocation
3     low     37  vocation
4  middle     31  vocation

In [7]:
x = list(df['ses'])

In [12]:
ses_num = []
for ctr in x:
    if ctr=='low':
        ses_num.append(0)
    elif ctr=='middle':
        ses_num.append(1)
    else:
        ses_num.append(2)

In [13]:
ses_num = [0 if i == 'low' else 1 if i == 'middle' else 2 for i in x]

In [14]:
ses_num == num

True

In [15]:
df['ses'] = ses_num

In [16]:
x_train,x_test,y_train,y_test = train_test_split(df.drop('prog',axis=1),df['prog'],test_size=0.2)

In [22]:
model = linear_model.LogisticRegression(multi_class = 'multinomial', solver='newton-cg').fit(x_train,y_train)

In [23]:
pred_y = model.predict(x_test)

In [24]:
confusion_matrix(y_test,pred_y)

array([[18,  0,  2],
       [ 8,  1,  1],
       [ 5,  0,  5]])

In [25]:
(18+1+5)/(20+10+10)

0.6

In [27]:
print(classification_report(y_test,pred_y))

              precision    recall  f1-score   support

    academic       0.58      0.90      0.71        20
     general       1.00      0.10      0.18        10
    vocation       0.62      0.50      0.56        10

    accuracy                           0.60        40
   macro avg       0.74      0.50      0.48        40
weighted avg       0.70      0.60      0.54        40



In [44]:
df = pd.read_excel('LogisticRegression.xlsx',sheet_name = 'ordinal2')

In [45]:
x_train,x_test,y_train,y_test = train_test_split(df.drop('Survival',axis=1),df['Survival'],test_size=0.2)

In [46]:
model = LogisticAT().fit(x_train,y_train)

In [47]:
pred_y = model.predict(x_test)

In [48]:
confusion_matrix(y_test,pred_y)

array([[0, 3, 0],
       [0, 9, 0],
       [0, 3, 0]])

In [49]:
12/(1+12+2)

0.8

In [52]:
print(classification_report(y_test,pred_y))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         3
           2       0.54      0.78      0.64         9
           3       0.00      0.00      0.00         3

    accuracy                           0.47        15
   macro avg       0.18      0.26      0.21        15
weighted avg       0.32      0.47      0.38        15



In [51]:
x1, x2, y1, y2 = train_test_split(df.drop('Survival', axis=1), df['Survival'], test_size=0.2)
mod2 = LogisticAT().fit(x1,y1)
pred_y = mod2.predict(x2)
print(confusion_matrix(y2,pred_y))
print(classification_report(y2,pred_y))

[[0 3 0]
 [1 8 0]
 [0 2 1]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         3
           2       0.62      0.89      0.73         9
           3       1.00      0.33      0.50         3

    accuracy                           0.60        15
   macro avg       0.54      0.41      0.41        15
weighted avg       0.57      0.60      0.54        15

